// Code generated by protoc-gen-go.
// source: query.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	query.proto

It has these top-level messages:
	QueryStruct
	MysqlResult
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type QueryStruct struct {
	Pool             *string  `protobuf:"bytes,1,req,name=pool" json:"pool,omitempty"`
	Sql              *string  `protobuf:"bytes,2,req,name=sql" json:"sql,omitempty"`
	Args             []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *QueryStruct) Reset()         { *m = QueryStruct{} }
func (m *QueryStruct) String() string { return proto1.CompactTextString(m) }
func (*QueryStruct) ProtoMessage()    {}

func (m *QueryStruct) GetPool() string {
	if m != nil && m.Pool != nil {
		return *m.Pool
	}
	return ""
}

func (m *QueryStruct) GetSql() string {
	if m != nil && m.Sql != nil {
		return *m.Sql
	}
	return ""
}

func (m *QueryStruct) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type MysqlResult struct {
	Rows             []*MysqlResult_Row `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
	Cols             []string           `protobuf:"bytes,2,rep,name=cols" json:"cols,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MysqlResult) Reset()         { *m = MysqlResult{} }
func (m *MysqlResult) String() string { return proto1.CompactTextString(m) }
func (*MysqlResult) ProtoMessage()    {}

func (m *MysqlResult) GetRows() []*MysqlResult_Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *MysqlResult) GetCols() []string {
	if m != nil {
		return m.Cols
	}
	return nil
}

type MysqlResult_Row struct {
	Values           []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MysqlResult_Row) Reset()         { *m = MysqlResult_Row{} }
func (m *MysqlResult_Row) String() string { return proto1.CompactTextString(m) }
func (*MysqlResult_Row) ProtoMessage()    {}

func (m *MysqlResult_Row) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
}
